# README
# Copy configuration file to ~/.config/alacritty/

# Install themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

[terminal.shell]
program = "/opt/homebrew/bin/fish"
# program = "/usr/local/bin/fish" -- para Mac Intel

[env]
TERM = "xterm-256color"

[window]
#padding.x = 10
#padding.y = 10
dimensions = { columns = 100, lines = 25 }
decorations = "Buttonless"

#opacity = 0.8
#blur = true

option_as_alt = "Both"

[font]
#normal.family = "MesloLGS Nerd Font Mono"
#normal.family = "JetBrainsMono Nerd Font Mono"
#normal.family = "FiraCode Nerd Font Mono"
#normal.family = "Hack Nerd font Mono"
#normal.family = "SauceCodePro Nerd Font Mono"
normal.family = "Inconsolata Nerd Font Mono"
#normal.style = "Thin"
normal.style = "Regular"
#normal.family = "MonaspiceNe Nerd Font Mono"
#normal.family = "Hack Nerd Font Mono"
#normal.family = "Maple Mono"
#normal.family = "JuliaMono"
#normal.family = "FiraMono Nerd Font Mono"

size = 20

[general]
import = [
    #"~/.config/alacritty/themes/themes/ashes_dark.toml"
    #"~/.config/alacritty/themes/themes/aura.toml"
    #"~/.config/alacritty/themes/themes/ayu_dark.toml"
    #"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/themes/citylights.toml"
    #"~/.config/alacritty/themes/themes/everforest_dark.toml"
    #"~/.config/alacritty/themes/themes/falcon.toml"
    #"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    #"~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
    #"~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
    #"~/.config/alacritty/themes/themes/hardhacker.toml"
    #"~/.config/alacritty/themes/themes/horizon-dark.toml"
    #"~/.config/alacritty/themes/themes/iterm.toml"
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
    #"~/.config/alacritty/themes/themes/kanagawa_wave.toml"
    #"~/.config/alacritty/themes/themes/Mariana.toml"
    #"~/.config/alacritty/themes/themes/nightfly.toml"
    #"~/.config/alacritty/themes/themes/nightfox.toml"
    #"~/.config/alacritty/themes/themes/night_owl.toml"
    #"~/.config/alacritty/themes/themes/nord.toml"
    #"~/.config/alacritty/themes/themes/nordic.toml"
    #"~/.config/alacritty/themes/themes/palenight.toml"
    #"~/.config/alacritty/themes/themes/pencil_dark.toml"
    #"~/.config/alacritty/themes/themes/remedy_dark.toml"
    #"~/.config/alacritty/themes/themes/rose-pine.toml"
    #"~/.config/alacritty/themes/themes/rose-pine.toml"
    #"~/.config/alacritty/themes/themes/rose-pine-moon.toml"
    #"~/.config/alacritty/themes/themes/seashells.toml"
    #"~/.config/alacritty/themes/themes/tokyo-night.toml"
    #"~/.config/alacritty/themes/themes/tomorrow_night.toml"
    #"~/.config/alacritty/themes/themes/wombat.toml"
]
